import axios from 'axios';
import layerCatalog from '../config/layerCatalog.json';
import { buildEarthEngineGeometryExpression, buildAoiFromCoordinateRing, parseSerializedAoi } from '../utils/aoi';
import { resolveBrowserEndpoint } from '../utils/runtimeUrls';

// API Base URL - in development, the proxy in package.json handles routing
const API_BASE = resolveBrowserEndpoint(process.env.REACT_APP_API_URL, '');

// Health check
export const healthCheck = async () => {
  const response = await axios.get(`${API_BASE}/health`);
  return response.data;
};

// Get default water map
export const getDefaultMap = async () => {
  const response = await axios.get(`${API_BASE}/api/maps/default`);
  return response.data;
};

// Get historical map data
export const getHistoricalMap = async (params) => {
  const response = await axios.post(`${API_BASE}/api/maps/historical`, params);
  return response.data;
};

export const getAgentRasterLayers = async (params) => {
  const response = await axios.post(`${API_BASE}/api/agent-raster-layers`, params);
  return response.data;
};

// Get unsupervised classification map
export const getUnsupervisedMap = async (params) => {
  const response = await axios.post(`${API_BASE}/api/maps/unsupervised`, params);
  return response.data;
};

// Get flood hotspot map
export const getFloodHotspotMap = async (params) => {
  const response = await axios.post(`${API_BASE}/api/maps/flood-hotspot`, params);
  return response.data;
};

// ChatGPT API
export const sendChatMessage = async (message) => {
  const response = await axios.post(`${API_BASE}/api/chat`, { message });
  return response.data;
};

// Get GEE Script
export const getGEEScript = async (message) => {
  const response = await axios.post(`${API_BASE}/api/scripts/gee`, { message });
  return response.data;
};

// Get PDF
export const getPDF = async () => {
  const response = await axios.get(`${API_BASE}/api/scripts/pdf`, { responseType: 'blob' });
  return response.data;
};

// Helper function to create GEE code snippet
export const createCodeSnippet = (params, dataType) => {
  const catalog = layerCatalog.basic;
  const aoi =
    parseSerializedAoi(params.aoi) ||
    buildAoiFromCoordinateRing(JSON.parse(params.coordinates || '[]'));

  if (!aoi) {
    return '';
  }

  const geometryExpression = buildEarthEngineGeometryExpression(aoi);
  const historicalCatalog = catalog.historical;
  const hotspotCatalog = catalog.hotspot;
  const supplementaryCatalog = catalog.supplementary;
  
  let code = `// Google Earth Engine Code for ${dataType} Analysis
// Generated by SATGPT

// Define Area of Interest
var geometry = ${geometryExpression};
var AoI = ee.FeatureCollection(ee.Feature(geometry));

// Time parameters
var time_start = '${params.time_start}';
var time_end = '${params.time_end}';

`;

  if (dataType === 'historical') {
    code += `// Historical Water Analysis using JRC Surface Water
var start_year = parseInt(time_start.split("-")[0]);
var end_year = parseInt(time_end.split("-")[0]);

var jrcSurfaceWater = ee.ImageCollection('${historicalCatalog.jrcYearlyHistory.dataset}')
    .filter(ee.Filter.calendarRange(start_year, end_year, 'year'))
    .map(function(image) { return image.select('${historicalCatalog.water.band}').eq(${historicalCatalog.water.matchValue}); })
    .sum()
    .clip(AoI);

var jrcSurfaceFlood = ee.ImageCollection('${historicalCatalog.jrcYearlyHistory.dataset}')
    .filter(ee.Filter.calendarRange(start_year, end_year, 'year'))
    .map(function(image) { return image.select('${historicalCatalog.flood.band}').eq(${historicalCatalog.flood.matchValue}); })
    .sum()
    .clip(AoI);

var LCLU = ee.ImageCollection('${supplementaryCatalog.landcover.dataset}').first().clip(AoI);
var PopulationDensity = ee.Image('${supplementaryCatalog.populationDensity.dataset}').clip(AoI);
PopulationDensity = PopulationDensity.visualize(${JSON.stringify(supplementaryCatalog.populationDensity.visualization)});
var SoilTexture = ee.Image('${supplementaryCatalog.soilTexture.dataset}').select('${supplementaryCatalog.soilTexture.band}').clip(AoI);
SoilTexture = SoilTexture.visualize(${JSON.stringify(supplementaryCatalog.soilTexture.visualization)});
var HealthCareAccess = ee.Image('${supplementaryCatalog.healthCareAccess.dataset}').select('${supplementaryCatalog.healthCareAccess.band}').clip(AoI);
HealthCareAccess = HealthCareAccess.visualize(${JSON.stringify(supplementaryCatalog.healthCareAccess.visualization)});

// Visualize
Map.centerObject(AoI, 10);
Map.addLayer(jrcSurfaceWater.updateMask(jrcSurfaceWater.gt(0)), 
             ${JSON.stringify(historicalCatalog.water.visualization)}, 'Permanent Water');
Map.addLayer(jrcSurfaceFlood.updateMask(jrcSurfaceFlood.gt(0)), 
             ${JSON.stringify(historicalCatalog.flood.visualization)}, 'Flood');
Map.addLayer(LCLU, {}, 'LCLU');
Map.addLayer(PopulationDensity, {}, 'Population Density');
Map.addLayer(SoilTexture, {}, 'Soil Texture');
Map.addLayer(HealthCareAccess, {}, 'Healthcare Access');
`;
  } else if (dataType === 'flood_hotspot') {
    code += `// Flood Hotspot Analysis
var year_from = ${params.year_from || 2000};
var year_count = ${params.year_count || 5};
var year_to = year_from + year_count;

var WaterESA2 = ee.ImageCollection('${hotspotCatalog.worldCoverPrimaryWater.dataset}').first().eq(${hotspotCatalog.worldCoverPrimaryWater.classValue}).selfMask();
var WaterESA1 = ee.ImageCollection('${hotspotCatalog.worldCoverLegacyWater.dataset}').first().eq(${hotspotCatalog.worldCoverLegacyWater.classValue}).selfMask();
var waterHistory = ee.ImageCollection("${hotspotCatalog.jrcYearlyHistory.dataset}")
    .filter(ee.Filter.calendarRange(year_from, year_to, 'year'));

var masks = waterHistory.map(function(image) { 
    return image.select('waterClass').eq(3); 
});

var PermanentWater = masks.sum();
var PermanentWaterFrequency = PermanentWater.divide(year_count);
var PermanentWaterFrequencyMap = PermanentWaterFrequency.gt(0).selfMask();
var PermanentWaterLayer = ee.ImageCollection([WaterESA1.rename('waterClass'), WaterESA2.rename('waterClass'), PermanentWaterFrequencyMap]).mosaic().clip(AoI);

var binary_masks = waterHistory.map(function(image) { 
    return image.select('waterClass').eq(2); 
});
var yearsWithWater = binary_masks.sum();
var floodFrequency = yearsWithWater.divide(year_count);
var floodFrequencyMap = floodFrequency.where(PermanentWaterLayer.eq(1), 0).selfMask().clip(AoI);
floodFrequencyMap = floodFrequencyMap.where(floodFrequencyMap.gt(0.9), 0.90);

var LCLU = ee.ImageCollection('${supplementaryCatalog.landcover.dataset}').first().clip(AoI);
var PopulationDensity = ee.Image('${supplementaryCatalog.populationDensity.dataset}').clip(AoI);
PopulationDensity = PopulationDensity.visualize(${JSON.stringify(supplementaryCatalog.populationDensity.visualization)});
var SoilTexture = ee.Image('${supplementaryCatalog.soilTexture.dataset}').select('${supplementaryCatalog.soilTexture.band}').clip(AoI);
SoilTexture = SoilTexture.visualize(${JSON.stringify(supplementaryCatalog.soilTexture.visualization)});
var HealthCareAccess = ee.Image('${supplementaryCatalog.healthCareAccess.dataset}').select('${supplementaryCatalog.healthCareAccess.band}').clip(AoI);
HealthCareAccess = HealthCareAccess.visualize(${JSON.stringify(supplementaryCatalog.healthCareAccess.visualization)});

Map.centerObject(AoI, 10);
Map.addLayer(PermanentWaterLayer, ${JSON.stringify(hotspotCatalog.water.visualization)}, 'Permanent Water');
Map.addLayer(floodFrequencyMap, ${JSON.stringify(hotspotCatalog.floodFrequency.visualization)}, 'Flood Frequency');
Map.addLayer(LCLU, {}, 'LCLU');
Map.addLayer(PopulationDensity, {}, 'Population Density');
Map.addLayer(SoilTexture, {}, 'Soil Texture');
Map.addLayer(HealthCareAccess, {}, 'Healthcare Access');
`;
  }

  return code;
};

const apiService = {
  healthCheck,
  getDefaultMap,
  getHistoricalMap,
  getAgentRasterLayers,
  getUnsupervisedMap,
  getFloodHotspotMap,
  sendChatMessage,
  getGEEScript,
  getPDF,
  createCodeSnippet,
};

export default apiService;
