import axios from 'axios';

// API Base URL - in development, the proxy in package.json handles routing
const API_BASE = process.env.REACT_APP_API_URL || '';

// Health check
export const healthCheck = async () => {
  const response = await axios.get(`${API_BASE}/flask-health-check`);
  return response.data;
};

// Get default water map
export const getDefaultMap = async () => {
  const response = await axios.get(`${API_BASE}/get_default`);
  return response.data;
};

// Get historical map data
export const getHistoricalMap = async (params) => {
  const response = await axios.get(`${API_BASE}/get_historical_map`, { params });
  return response.data;
};

// Get unsupervised classification map
export const getUnsupervisedMap = async (params) => {
  const response = await axios.get(`${API_BASE}/get_unsupervised_map`, { params });
  return response.data;
};

// Get flood hotspot map
export const getFloodHotspotMap = async (params) => {
  const response = await axios.get(`${API_BASE}/get_flood_hotspot_map`, { params });
  return response.data;
};

// ChatGPT API
export const sendChatMessage = async (message) => {
  const response = await axios.post(`${API_BASE}/chatGPT`, { message });
  return response.data;
};

// Get GEE Script
export const getGEEScript = async (message) => {
  const response = await axios.post(`${API_BASE}/get_script`, { message });
  return response.data;
};

// Get PDF
export const getPDF = async () => {
  const response = await axios.get(`${API_BASE}/get_pdf`, { responseType: 'blob' });
  return response.data;
};

// Helper function to create GEE code snippet
export const createCodeSnippet = (params, dataType) => {
  const geoJsonList = JSON.parse(params.AoI_cords);
  
  let code = `// Google Earth Engine Code for ${dataType} Analysis
// Generated by SATGPT

// Define Area of Interest
var geometry = ee.Geometry.Polygon(${JSON.stringify(geoJsonList)});
var AoI = ee.FeatureCollection(ee.Feature(geometry));

// Time parameters
var time_start = '${params.time_start}';
var time_end = '${params.time_end}';

`;

  if (dataType === 'historical') {
    code += `// Historical Water Analysis using JRC Surface Water
var start_year = parseInt(time_start.split("-")[0]);
var end_year = parseInt(time_end.split("-")[0]);

var jrcSurfaceWater = ee.ImageCollection('JRC/GSW1_3/YearlyHistory')
    .filter(ee.Filter.calendarRange(start_year, end_year, 'year'))
    .map(function(image) { return image.select('waterClass').eq(3); })
    .sum()
    .clip(AoI);

var jrcSurfaceFlood = ee.ImageCollection('JRC/GSW1_3/YearlyHistory')
    .filter(ee.Filter.calendarRange(start_year, end_year, 'year'))
    .map(function(image) { return image.select('waterClass').eq(2); })
    .sum()
    .clip(AoI);

// Visualize
Map.centerObject(AoI, 10);
Map.addLayer(jrcSurfaceWater.updateMask(jrcSurfaceWater.gt(0)), 
             {min: 0, max: 1, palette: ['#00008B']}, 'Permanent Water');
Map.addLayer(jrcSurfaceFlood.updateMask(jrcSurfaceFlood.gt(0)), 
             {min: 0, max: 1, palette: ['#FD0303']}, 'Flood');
`;
  } else if (dataType === 'flood_hotspot') {
    code += `// Flood Hotspot Analysis
var year_from = ${params.year_from || 2000};
var year_count = ${params.year_count || 5};
var year_to = year_from + year_count;

var waterHistory = ee.ImageCollection("JRC/GSW1_4/YearlyHistory")
    .filter(ee.Filter.calendarRange(year_from, year_to, 'year'));

var masks = waterHistory.map(function(image) { 
    return image.select('waterClass').eq(3); 
});

var PermanentWater = masks.sum();
var PermanentWaterFrequency = PermanentWater.divide(year_count);
var PermanentWaterFrequencyMap = PermanentWaterFrequency.gt(0).selfMask();

var binary_masks = waterHistory.map(function(image) { 
    return image.select('waterClass').eq(2); 
});
var yearsWithWater = binary_masks.sum();
var floodFrequency = yearsWithWater.divide(year_count);

var pink = ['#ffa9bb', '#ff9cac', '#ff8f9e', '#ff8190', '#ff7281', '#ff6171', '#ff4f61', '#ff3b50', '#ff084a'];

Map.centerObject(AoI, 10);
Map.addLayer(PermanentWaterFrequencyMap.clip(AoI), 
             {min: 0, max: 1, palette: ['#00008B']}, 'Permanent Water');
Map.addLayer(floodFrequency.clip(AoI), 
             {min: 0.1, max: 0.8, palette: pink}, 'Flood Frequency');
`;
  }

  return code;
};

export default {
  healthCheck,
  getDefaultMap,
  getHistoricalMap,
  getUnsupervisedMap,
  getFloodHotspotMap,
  sendChatMessage,
  getGEEScript,
  getPDF,
  createCodeSnippet,
};
