// Flood Analysis - 2024 Thailand Chiang Mai Flood
// S1 SAR Otsu Change Detection | Generated by FloodAgent

// ============================================================
// Block 1: Parameters & AOI
// ============================================================
var pre_date = '2024-09-15';
var peek_date = '2024-10-05';
var days_range = 15;

var AOI = ee.Geometry.Polygon([[
  [98.5671, 19.1071], [99.2037, 19.1071],
  [99.2037, 18.5601], [98.5671, 18.5601],
  [98.5671, 19.1071]
]]);

Map.centerObject(AOI, 10);
Map.addLayer(ee.FeatureCollection(AOI).style({color: 'yellow', fillColor: '00000000', width: 2}), {}, 'AOI Boundary');
print('AOI area (km²):', AOI.area().divide(1e6));

// ============================================================
// Block 2: S1 Pre-flood Image
// ============================================================
var vv_pre = ee.ImageCollection('COPERNICUS/S1_GRD')
  .filterDate(ee.Date(pre_date).advance(-days_range, 'day'), ee.Date(pre_date))
  .filterBounds(AOI)
  .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'))
  .filter(ee.Filter.eq('instrumentMode', 'IW'))
  .select('VV').median().clip(AOI);

Map.addLayer(vv_pre, {min: -25, max: 0}, 'S1 Pre-flood');

// ============================================================
// Block 3: S1 Peak-flood Image
// ============================================================
var vv_peek = ee.ImageCollection('COPERNICUS/S1_GRD')
  .filterDate(ee.Date(peek_date), ee.Date(peek_date).advance(days_range, 'day'))
  .filterBounds(AOI)
  .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'))
  .filter(ee.Filter.eq('instrumentMode', 'IW'))
  .select('VV').median().clip(AOI);

Map.addLayer(vv_peek, {min: -25, max: 0}, 'S1 Peak-flood');

// ============================================================
// Block 4: SAR Change Index
// ============================================================
var change = vv_peek.subtract(vv_pre).rename('change');

var changeLayer = ui.Map.Layer(change, {min: -5, max: 5, palette: ['blue','white','red']}, 'Change Index');
Map.add(changeLayer);

// ============================================================
// Block 5: Otsu Threshold Calculation
// ============================================================
// Otsu: find threshold that maximizes between-class variance
var hist = change.reduceRegion({
  reducer: ee.Reducer.histogram(255, 0.2), geometry: AOI,
  scale: 30, maxPixels: 1e9, bestEffort: true
});
var counts = ee.Array(ee.Dictionary(hist.get('change')).get('histogram'));
var means = ee.Array(ee.Dictionary(hist.get('change')).get('bucketMeans'));
var size = means.length().get([0]);
var total = counts.reduce(ee.Reducer.sum(), [0]).get([0]);
var sumAll = counts.multiply(means).reduce(ee.Reducer.sum(), [0]).get([0]);

var threshold = ee.Dictionary(ee.List.sequence(0, size.subtract(1)).iterate(function(i, state) {
  state = ee.Dictionary(state); i = ee.Number(i);
  var w0 = state.getNumber('w0').add(counts.get([i]));
  var sum0 = state.getNumber('sum0').add(counts.get([i]).multiply(means.get([i])));
  var w1 = total.subtract(w0);
  var valid = w0.gt(0).and(w1.gt(0));
  var bv = valid.multiply(w0.multiply(w1).multiply(
    sum0.divide(w0).subtract(sumAll.subtract(sum0).divide(w1)).pow(2)));
  var isMax = bv.gt(state.getNumber('maxVar'));
  return ee.Dictionary({
    w0: w0, sum0: sum0,
    maxVar: isMax.multiply(bv).add(isMax.not().multiply(state.getNumber('maxVar'))),
    bestT: isMax.multiply(means.get([i])).add(isMax.not().multiply(state.getNumber('bestT')))
  });
}, ee.Dictionary({w0: 0, sum0: 0, maxVar: 0, bestT: -3}))).getNumber('bestT');

print('Otsu threshold (dB):', threshold);

// ============================================================
// Block 6: Flood Result & Statistics
// ============================================================
Map.remove(changeLayer);

var flood_change = change.lt(threshold);
var permanent = ee.Image('JRC/GSW1_4/GlobalSurfaceWater').select('occurrence').gte(95).clip(AOI);
var flood_area = flood_change.and(permanent.not());

Map.addLayer(permanent.selfMask(), {palette: ['00008B']}, 'Permanent Water');
Map.addLayer(flood_area.selfMask(), {palette: ['ff0000']}, 'Flood Extent');

var area_km2 = flood_area.multiply(ee.Image.pixelArea().divide(1e6)).reduceRegion({
  reducer: ee.Reducer.sum(), geometry: AOI, scale: 30, maxPixels: 1e9, bestEffort: true
});
print('Flood area (km²):', area_km2);
