"""
GEE 代码生成器
根据用户提问的洪水事件参数，生成可在 GEE Code Editor 中直接运行的 JavaScript 代码
"""
import json
from typing import Optional, Dict, Any, List, Tuple


def generate_flood_gee_code(
    event_name: str,
    pre_date: str,
    peek_date: str,
    location: str,
    coordinates: Optional[List[float]] = None,
    bounds: Optional[Dict[str, float]] = None,
    geojson: Optional[Dict[str, Any]] = None,
    days_range: int = 15
) -> str:
    """
    生成洪水分析的 GEE JavaScript 代码

    Args:
        event_name: 洪水事件名称
        pre_date: 洪水前日期 (YYYY-MM-DD)
        peek_date: 洪峰日期 (YYYY-MM-DD)
        location: 地点名称
        coordinates: 中心点 [lon, lat]
        bounds: 边界框 {"west", "south", "east", "north"}
        geojson: GeoJSON Feature/Geometry 对象
        days_range: 搜索窗口天数

    Returns:
        完整的 GEE JavaScript 代码字符串
    """
    # 生成 AOI 代码
    aoi_code = _build_aoi_code(coordinates, bounds, geojson)

    return f"""// Flood Analysis - {event_name}
// S1 SAR Otsu Change Detection | Generated by FloodAgent

// ============================================================
// Block 1: Parameters & AOI
// ============================================================
var pre_date = '{pre_date}';
var peek_date = '{peek_date}';
var days_range = {days_range};

{aoi_code}

Map.centerObject(AOI, 10);
Map.addLayer(ee.FeatureCollection(AOI).style({{color: 'yellow', fillColor: '00000000', width: 2}}), {{}}, 'AOI Boundary');
print('AOI area (km²):', AOI.area().divide(1e6));

// ============================================================
// Block 2: S1 Pre-flood Image
// ============================================================
var vv_pre = ee.ImageCollection('COPERNICUS/S1_GRD')
  .filterDate(ee.Date(pre_date).advance(-days_range, 'day'), ee.Date(pre_date))
  .filterBounds(AOI)
  .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'))
  .filter(ee.Filter.eq('instrumentMode', 'IW'))
  .select('VV').median().clip(AOI);

Map.addLayer(vv_pre, {{min: -25, max: 0}}, 'S1 Pre-flood');

// ============================================================
// Block 3: S1 Peak-flood Image
// ============================================================
var vv_peek = ee.ImageCollection('COPERNICUS/S1_GRD')
  .filterDate(ee.Date(peek_date), ee.Date(peek_date).advance(days_range, 'day'))
  .filterBounds(AOI)
  .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'))
  .filter(ee.Filter.eq('instrumentMode', 'IW'))
  .select('VV').median().clip(AOI);

Map.addLayer(vv_peek, {{min: -25, max: 0}}, 'S1 Peak-flood');

// ============================================================
// Block 4: SAR Change Index
// ============================================================
var change = vv_peek.subtract(vv_pre).rename('change');

var changeLayer = ui.Map.Layer(change, {{min: -5, max: 5, palette: ['blue','white','red']}}, 'Change Index');
Map.add(changeLayer);

// ============================================================
// Block 5: Otsu Threshold Calculation
// ============================================================
// Otsu: find threshold that maximizes between-class variance
var hist = change.reduceRegion({{
  reducer: ee.Reducer.histogram(255, 0.2), geometry: AOI,
  scale: 30, maxPixels: 1e9, bestEffort: true
}});
var counts = ee.Array(ee.Dictionary(hist.get('change')).get('histogram'));
var means = ee.Array(ee.Dictionary(hist.get('change')).get('bucketMeans'));
var size = means.length().get([0]);
var total = counts.reduce(ee.Reducer.sum(), [0]).get([0]);
var sumAll = counts.multiply(means).reduce(ee.Reducer.sum(), [0]).get([0]);

var threshold = ee.Dictionary(ee.List.sequence(0, size.subtract(1)).iterate(function(i, state) {{
  state = ee.Dictionary(state); i = ee.Number(i);
  var w0 = state.getNumber('w0').add(counts.get([i]));
  var sum0 = state.getNumber('sum0').add(counts.get([i]).multiply(means.get([i])));
  var w1 = total.subtract(w0);
  var valid = w0.gt(0).and(w1.gt(0));
  var bv = valid.multiply(w0.multiply(w1).multiply(
    sum0.divide(w0).subtract(sumAll.subtract(sum0).divide(w1)).pow(2)));
  var isMax = bv.gt(state.getNumber('maxVar'));
  return ee.Dictionary({{
    w0: w0, sum0: sum0,
    maxVar: isMax.multiply(bv).add(isMax.not().multiply(state.getNumber('maxVar'))),
    bestT: isMax.multiply(means.get([i])).add(isMax.not().multiply(state.getNumber('bestT')))
  }});
}}, ee.Dictionary({{w0: 0, sum0: 0, maxVar: 0, bestT: -3}}))).getNumber('bestT');

print('Otsu threshold (dB):', threshold);

// ============================================================
// Block 6: Flood Result & Statistics
// ============================================================
Map.remove(changeLayer);

var flood_change = change.lt(threshold);
var permanent = ee.Image('JRC/GSW1_4/GlobalSurfaceWater').select('occurrence').gte(95).clip(AOI);
var flood_area = flood_change.and(permanent.not());

Map.addLayer(permanent.selfMask(), {{palette: ['00008B']}}, 'Permanent Water');
Map.addLayer(flood_area.selfMask(), {{palette: ['ff0000']}}, 'Flood Extent');

var area_km2 = flood_area.multiply(ee.Image.pixelArea().divide(1e6)).reduceRegion({{
  reducer: ee.Reducer.sum(), geometry: AOI, scale: 30, maxPixels: 1e9, bestEffort: true
}});
print('Flood area (km²):', area_km2);"""


def _build_aoi_code(
    coordinates: Optional[List[float]] = None,
    bounds: Optional[Dict[str, float]] = None,
    geojson: Optional[Dict[str, Any]] = None
) -> str:
    """
    根据不同的地理数据生成 AOI 定义代码

    优先级: geojson > bounds > coordinates
    """
    # 优先使用 GeoJSON 精确边界
    if geojson:
        geometry = _extract_geometry(geojson)
        if geometry:
            geo_type = geometry.get("type", "")
            coords = geometry.get("coordinates", [])
            coords_json = json.dumps(coords)

            if geo_type == "Polygon":
                return f"var AOI = ee.Geometry.Polygon({coords_json});"
            elif geo_type == "MultiPolygon":
                return f"var AOI = ee.Geometry.MultiPolygon({coords_json});"
            elif geo_type == "Point":
                # 点的话加缓冲区
                lon, lat = coords
                return (
                    f"var AOI = ee.Geometry.Point([{lon}, {lat}]).buffer(50000);\n"
                    f"// Buffered 50km around point"
                )

    # 使用边界框
    if bounds:
        w = bounds.get("west", 0)
        s = bounds.get("south", 0)
        e = bounds.get("east", 0)
        n = bounds.get("north", 0)
        return (
            f"var AOI = ee.Geometry.Rectangle([{w}, {s}, {e}, {n}]);"
        )

    # 使用中心点 + 缓冲区
    if coordinates and len(coordinates) == 2:
        lon, lat = coordinates
        return (
            f"var AOI = ee.Geometry.Point([{lon}, {lat}]).buffer(50000);\n"
            f"// Buffered 50km around center point"
        )

    # 兜底
    return "var AOI = Map.getBounds(true); // Please define your AOI"


def _extract_geometry(geojson: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """从各种 GeoJSON 格式中提取 geometry"""
    geo_type = geojson.get("type", "")

    if geo_type == "FeatureCollection":
        features = geojson.get("features", [])
        if features:
            return features[0].get("geometry")
    elif geo_type == "Feature":
        return geojson.get("geometry")
    elif geo_type in ("Polygon", "MultiPolygon", "Point"):
        return geojson

    return None
